"""
CASPER Environment Variable Management Service
Secure environment variable management with encryption and synchronization.
"""

import os
import json
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Any
from datetime import datetime
from cryptography.fernet import Fernet

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.prompt import Prompt, Confirm

console = Console()


class EnvironmentManager:
    """Manages environment variables with encryption and synchronization."""

    def __init__(self):
        self.console = Console()
        self.project_root = Path.cwd()
        self.env_dir = self.project_root / ".casper" / "env"
        self.env_dir.mkdir(parents=True, exist_ok=True)

        # Environment files
        self.env_file = self.project_root / ".env"
        self.env_example_file = self.project_root / ".env.example"
        self.encrypted_file = self.env_dir / "env.encrypted"
        self.key_file = self.env_dir / "env.key"
        self.config_file = self.env_dir / "config.json"

        self._ensure_key_exists()

    def _ensure_key_exists(self):
        """Ensure encryption key exists."""
        if not self.key_file.exists():
            key = Fernet.generate_key()
            with open(self.key_file, "wb") as f:
                f.write(key)
            os.chmod(self.key_file, 0o600)

    def _get_cipher(self) -> Fernet:
        """Get encryption cipher."""
        with open(self.key_file, "rb") as f:
            key = f.read()
        return Fernet(key)

    def _load_env_file(self, file_path: Path) -> Dict[str, str]:
        """Load environment variables from file."""
        env_vars = {}
        if file_path.exists():
            with open(file_path, "r") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, value = line.split("=", 1)
                        env_vars[key.strip()] = value.strip().strip("'\"")
        return env_vars

    def _save_env_file(self, env_vars: Dict[str, str], file_path: Path):
        """Save environment variables to file."""
        with open(file_path, "w") as f:
            f.write(f"# Environment variables - Generated by CASPER\n")
            f.write(f"# Last updated: {datetime.now().isoformat()}\n\n")

            for key, value in sorted(env_vars.items()):
                # Quote values that contain spaces or special characters
                if " " in value or any(c in value for c in ["$", '"', "'", "\\", "\n"]):
                    value = f'"{value}"'
                f.write(f"{key}={value}\n")

    async def list_variables(self, show_values: bool = False) -> bool:
        """List environment variables."""
        try:
            env_vars = self._load_env_file(self.env_file)

            if not env_vars:
                console.print("[yellow]⚠️ No environment variables found[/yellow]")
                if not self.env_file.exists():
                    console.print(
                        f"[dim]Create {self.env_file.name} to get started[/dim]"
                    )
                return True

            table = Table(
                title="🌍 Environment Variables",
                show_header=True,
                header_style="bold cyan",
            )
            table.add_column("Variable", style="yellow")
            table.add_column("Value", style="white" if show_values else "dim")
            table.add_column("Source", style="dim")

            for key, value in sorted(env_vars.items()):
                display_value = value if show_values else "*" * min(len(value), 8)
                source = "System" if key in os.environ else "Local"
                table.add_row(key, display_value, source)

            console.print(table)

            if not show_values:
                console.print(
                    "[dim]Use '/env list --values' to show actual values[/dim]"
                )

            return True

        except Exception as e:
            console.print(f"[red]❌ Error listing variables: {str(e)}[/red]")
            return False

    async def set_variable(self, key: str, value: str) -> bool:
        """Set an environment variable."""
        try:
            if not key or not key.isidentifier():
                console.print(
                    "[red]❌ Invalid variable name. Use letters, numbers, and underscores only.[/red]"
                )
                return False

            env_vars = self._load_env_file(self.env_file)

            # Check if variable already exists
            if key in env_vars:
                if not Confirm.ask(
                    f"[yellow]Variable '{key}' already exists. Overwrite?[/yellow]",
                    default=False,
                ):
                    console.print("[dim]→ Operation cancelled[/dim]")
                    return False

            env_vars[key] = value
            self._save_env_file(env_vars, self.env_file)

            console.print(
                f"[green]✅ Set {key}={value[:20]}{'...' if len(value) > 20 else ''}[/green]"
            )

            # Update .env.example file
            await self._update_example_file(env_vars)

            return True

        except Exception as e:
            console.print(f"[red]❌ Error setting variable: {str(e)}[/red]")
            return False

    async def get_variable(self, key: str) -> bool:
        """Get a specific environment variable."""
        try:
            env_vars = self._load_env_file(self.env_file)

            if key not in env_vars:
                console.print(f"[red]❌ Variable '{key}' not found[/red]")
                return False

            value = env_vars[key]
            console.print(
                Panel(
                    f"[bold yellow]{key}[/bold yellow] = [white]{value}[/white]",
                    title="🔍 Environment Variable",
                    border_style="green",
                )
            )

            return True

        except Exception as e:
            console.print(f"[red]❌ Error getting variable: {str(e)}[/red]")
            return False

    async def delete_variable(self, key: str) -> bool:
        """Delete an environment variable."""
        try:
            env_vars = self._load_env_file(self.env_file)

            if key not in env_vars:
                console.print(f"[red]❌ Variable '{key}' not found[/red]")
                return False

            if not Confirm.ask(f"[red]Delete variable '{key}'?[/red]", default=False):
                console.print("[dim]→ Operation cancelled[/dim]")
                return False

            del env_vars[key]
            self._save_env_file(env_vars, self.env_file)

            console.print(f"[green]✅ Deleted variable '{key}'[/green]")

            # Update .env.example file
            await self._update_example_file(env_vars)

            return True

        except Exception as e:
            console.print(f"[red]❌ Error deleting variable: {str(e)}[/red]")
            return False

    async def encrypt_env(self) -> bool:
        """Encrypt environment file."""
        try:
            if not self.env_file.exists():
                console.print("[red]❌ .env file not found[/red]")
                return False

            with open(self.env_file, "rb") as f:
                env_data = f.read()

            cipher = self._get_cipher()
            encrypted_data = cipher.encrypt(env_data)

            with open(self.encrypted_file, "wb") as f:
                f.write(encrypted_data)

            os.chmod(self.encrypted_file, 0o600)

            console.print(
                f"[green]✅ Environment file encrypted to {self.encrypted_file.relative_to(self.project_root)}[/green]"
            )
            console.print(
                "[dim]→ You can now safely commit the encrypted file to version control[/dim]"
            )

            return True

        except Exception as e:
            console.print(f"[red]❌ Error encrypting environment: {str(e)}[/red]")
            return False

    async def decrypt_env(self) -> bool:
        """Decrypt environment file."""
        try:
            if not self.encrypted_file.exists():
                console.print("[red]❌ No encrypted environment file found[/red]")
                return False

            if self.env_file.exists():
                if not Confirm.ask(
                    "[yellow]Existing .env file will be overwritten. Continue?[/yellow]",
                    default=False,
                ):
                    console.print("[dim]→ Operation cancelled[/dim]")
                    return False

            with open(self.encrypted_file, "rb") as f:
                encrypted_data = f.read()

            cipher = self._get_cipher()
            decrypted_data = cipher.decrypt(encrypted_data)

            with open(self.env_file, "wb") as f:
                f.write(decrypted_data)

            console.print(
                f"[green]✅ Environment file decrypted to {self.env_file.name}[/green]"
            )

            return True

        except Exception as e:
            console.print(f"[red]❌ Error decrypting environment: {str(e)}[/red]")
            return False

    async def _update_example_file(self, env_vars: Dict[str, str]):
        """Update .env.example file with variable names."""
        example_vars = {}

        for key in env_vars.keys():
            # Don't expose actual values in example file
            if (
                key.endswith("_KEY")
                or key.endswith("_SECRET")
                or key.endswith("_TOKEN")
            ):
                example_vars[key] = "your-secret-here"
            elif key.endswith("_URL") or key.endswith("_ENDPOINT"):
                example_vars[key] = "https://your-service.com"
            elif key.endswith("_PORT"):
                example_vars[key] = "3000"
            elif key in ["DEBUG", "DEV_MODE"]:
                example_vars[key] = "true"
            else:
                example_vars[key] = f"your-{key.lower().replace('_', '-')}-value"

        self._save_env_file(example_vars, self.env_example_file)

    async def sync_environments(self) -> bool:
        """Synchronize environment variables across different environments."""
        try:
            console.print("[dim]→ Checking environment synchronization...[/dim]")

            # Check for common environment files
            env_files = {
                "development": self.project_root / ".env",
                "staging": self.project_root / ".env.staging",
                "production": self.project_root / ".env.production",
                "testing": self.project_root / ".env.test",
            }

            existing_files = {
                name: path for name, path in env_files.items() if path.exists()
            }

            if len(existing_files) <= 1:
                console.print(
                    "[yellow]⚠️ Only one environment file found. Nothing to sync.[/yellow]"
                )
                return True

            console.print(
                f"[green]✓[/green] Found {len(existing_files)} environment files"
            )

            # Load all environment variables
            all_vars = {}
            for env_name, env_path in existing_files.items():
                all_vars[env_name] = self._load_env_file(env_path)

            # Find common and unique variables
            all_keys = set()
            for vars_dict in all_vars.values():
                all_keys.update(vars_dict.keys())

            common_keys = set(all_vars[list(all_vars.keys())[0]].keys())
            for vars_dict in all_vars.values():
                common_keys &= set(vars_dict.keys())

            unique_keys = {}
            for env_name, vars_dict in all_vars.items():
                unique_keys[env_name] = set(vars_dict.keys()) - common_keys

            # Display sync report
            table = Table(
                title="🔄 Environment Sync Report",
                show_header=True,
                header_style="bold cyan",
            )
            table.add_column("Environment", style="yellow")
            table.add_column("Variables", style="white")
            table.add_column("Unique", style="red")

            for env_name, vars_dict in all_vars.items():
                unique_count = len(unique_keys[env_name])
                unique_text = f"+{unique_count}" if unique_count > 0 else ""
                table.add_row(env_name, str(len(vars_dict)), unique_text)

            console.print(table)

            if any(unique_keys.values()):
                console.print(
                    f"\n[yellow]⚠️ Found environment-specific variables[/yellow]"
                )
                for env_name, keys in unique_keys.items():
                    if keys:
                        console.print(
                            f"[dim]{env_name}:[/dim] {', '.join(sorted(keys))}"
                        )

            return True

        except Exception as e:
            console.print(f"[red]❌ Error syncing environments: {str(e)}[/red]")
            return False


# Global instance
env_manager = EnvironmentManager()
